# Generated by Django 4.2.27 on 2025-12-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('assignment', 'Task Assignment'), ('comment', 'Comment'), ('team_added', 'Team Added'), ('file_uploaded', 'File Uploaded')], max_length=20),
        ),
    ]
